# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asId', models.IntegerField(default=0)),
                ('statu', models.CharField(default='', max_length=20, null=True, verbose_name='\u95f2\u7f6e')),
                ('ip', models.CharField(blank=True, default='0.0.0.0', max_length=32, null=True)),
                ('cpu', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20, null=True)),
                ('YP', models.CharField(max_length=20, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.TextField(blank=True, max_length=100, null=True)),
                ('bgtime', models.DateTimeField(auto_now=True, null=True)),
                ('edtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(1, 'admin'), (2, 'system'), (3, 'customer'), (0, 'commonly')], default=0)),
                ('rgtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, '\u4e00\u7ea7\u7528\u6237'), (2, '\u4e8c\u7ea7\u7528\u6237'), (3, '\u4e09\u7ea7\u7528\u6237'), (4, '\u56db\u7ea7\u7528\u6237'), (0, '\u672a\u5206\u914d')], default=0, max_length=20, null=True)),
                ('remark', models.CharField(default='', max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(choices=[(1, '\u4e00\u7ea7\u7528\u6237'), (2, '\u4e8c\u7ea7\u7528\u6237'), (3, '\u4e09\u7ea7\u7528\u6237'), (4, '\u56db\u7ea7\u7528\u6237'), (0, '\u672a\u5206\u914d')], default=0, max_length=20, null=True)),
                ('assets', models.TextField(default='', max_length=100, null=True)),
                ('remark', models.TextField(default='', max_length=100, null=True)),
            ],
        ),
    ]
